### Get a customer
GET http://localhost:3000/customers/2

### List all customers
GET http://localhost:3000/customers

### Create a new customer
POST http://localhost:3000/customers
content-type: application/json

{
    "firstName": "Tom",
    "lastName": "Smith",
    "email": "Tom@test.com"
}

### Find a customer by their email
GET http://localhost:3000/customers?email=Tom@test.com


### Update a user
PATCH http://localhost:3000/customers/2

{
    "firstName": "Fred",
    "lastName": "Davis",
    "email": "fred@test.com",
}

### Delete a user
DELETE http://localhost:3000/customers/1
